server:
  port: 9050
  servlet.context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: account_user
    password: account_password
    driver-class-name: org.postgresql.Driver

stripe:
  api:
    secret: sk_test_51TrZ59KibACKXiAvCXdg67zeSR4eWJ4O5rprbc3fexBYWrQrNEvyJt6c00cyN5a980EZjizgiIDKwwGW0dpHtxy500nn8cT0Nd
  webhook:
    secret: whsec_4d2a9508363c009568e2d731e897afe45371e860f8087135ae57e767ccf5fe12

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://pgvector.lovable-core.svc.cluster.local:5432/account_db
    username: account_user
    password: ${DB_PASSWORD}


stripe:
  api:
    secret: ${STRIPE_API_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}