server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intelligence_db
    username: intelligence_user
    password: intelligence_password
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          #          model: x-ai/grok-code-fast-1
          model: openai/gpt-4o-mini
          temperature: 0.0

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://pgvector.lovable-core.svc.cluster.local:5432/intelligence_db
    username: intelligence_user
    password: ${DB_PASSWORD}
  ai:
    openai:
      api-key: ${AI_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          #          model: x-ai/grok-code-fast-1
          model: openai/gpt-4o-mini
          temperature: 0.0